# Generated by Django 5.2.6 on 2025-11-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='payout_status',
            field=models.CharField(choices=[('none', 'None'), ('requested', 'Requested'), ('approved', 'Approved')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_paid_out',
            field=models.BooleanField(default=False),
        ),
    ]
